### ISSUE TITLE
How to process AsyncRequest Response?

### ISSUE THREAD

**Issue by 6220119** [ntnhan94/restautomationfwk#1]
Should the interface need another method to process AsyncRequest Response?

https://github.com/ntnhan94/restautomationfwk/blob/master/src/main/java/com/tma/ov/automation/rest/api/ResponseCallback.java#L5

**Comment by ntnhan94** [comment]
I combined 2 APIs to unique API: call method. This method will be treated as Sync method even if it can be sync or async inside the body
